---
title: "Lecture 11"
author: "David Zynda"
date: "September 27, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Theorem 1:

_Suppose preferences are responsive. A matching $\mu$ is group stable if and only if it is pairwise stable_

It should be clear that if responsive preferences are not group stable, then they cannot be pairwise stable. If they are not group stable, then there is some coalition $C$ that blocks $\mu$. That coalition will have agents who would rather be alone ($\mu$ not IR) or rather be with another agent on the other side of the market (blocking pair). Hence, it will not be pairwise stable. 

To show: if responsive preferences are pairwise stable, then they are group stable. 

Take Contrapositive: If responsive preferences are not group stable, then they are not pairwise stable. Assume $\mu$ is not group stable, but $\mu$ is IR. But if $\mu$ is not IR, then it is not pairwise stable, and we are done. 


Given $\mu$ is not group stable, there exists by definition some $C \ne \emptyset$ such that $C$ blocks $\mu$ via $\\mu'$. In other words, $\mu'$ dominates $\mu$ via $C$.


__Claim:__ There exists some $t \in C \cap T$ such that $\mu'(t) \cap C \ne \emptyset$. 

First notice the following if the above were not true. If $C \subseteq B$: then $\mu'(b) = b$ for each $b \in C$. Then, $b = \mu'(b) \succ_b \mu(b)$ for each $b \in C$. Then, we contradict our assumption of individual rationality made above.  

So, we now know that $C \cap T \ne \emptyset$. In fact, for $t \in C \cap T: \mu'(t) \cap C \ne \emptyset$. If this were not so, then there is a $t \in C \cap T$ such that both statements are true:

(1) Either $\mu'(t) = t$ or $\mu'(t) \subseteq \mu(t)$ ($t$ is matched with himself or he is matched with an old matching under $\mu$). 
(2) And $\mu'(t) \succ_t \mu(t)$. 

Notice, that the first part of the first condition cannot be, since we assumed IR. And, the second part implies that some $b$ is left alone and matches with himself, also breaking the IR assumption. So, the claim stands. 

__Two Cases:__

(1) $|\mu'(t) \le |\mu(t)|$.
(2) $|\mu'(t)| > |\mu(t)|$. 



__Case 1:__

We have responsive preferences. We also have that $\mu'(t) \setminus \mu(t) \ne \emptyset$. This is because we showed above that $\mu'(t) \cap C \ne \emptyset$. 


Note the following:

$$B_1 = \mu'(t)$$
$$B_2 = \mu(t)$$
$$\mu'(t) \setminus \mu(t) = B_1 \setminus B_2 \ne \emptyset$$
$$|B_2| = |\mu(t)| \ge |\mu'(t)| = |B_1|$$

For each $\hat{B} \subseteq B_2$ we have $\mu(t) \succ_t \hat{B}$. We know this since $\mu$ is IR. And of course $\mu'(t) \succ_t \mu(t)$. 

Now, apply Lemma 1: 

Need to finish notes. 




