---
title: "Lecture 3"
author: "David Zynda"
date: "August 28, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Theorem: Gale-Shapley (1962):

_In any one-to-one matching environment there exists a stable matching $\mu$._ 

The proof is constructive such that it makes a stable matching $\mu$ as it employs the T-proposal Deferred Acceptance Algorithm. 

__Sketch of Algorithm__

1. Each T agent proposes to her most preferred B agent if there is one that is acceptable to her. Each B agent tentatively holds on to the most preferred proposal provided that there is one acceptable to her.
2. Denote this step as $k \ge 2$. Each T agent that was rejected at Step $k-1$ makes the proposal to her next highest acceptable choice if there is one. And each B agent tentatively holds on to her most preferred option amongst new proposals plus $k-1$ held proposals if there is one acceptable. All other proposals are rejected. 

Algorithm will terminate when: $k = k+1$





Fix $X \subset J$ where $J$ is a set of agents. Write $\max_i X = \{j \in X| j \succsim_i j' :\forall j' \in X\}$

If $X = \emptyset$ then $\max_i X = \emptyset$




Formally, the Algorithm can be written as follows:

__Round 1:__

$$A^1(t) = A(t)$$ 
T ask what agents are acceptable to me in round 1?
 
 
 
 
$$\hat{P}^1 : T  \rightarrow B \cup \{\emptyset\} : \hat{P}^1 \in \max_t A^1(t)$$ 

I want to make proposal to best B agent. T is matched with best B agent or keeps to himself (empty set). 



If $A^1(t) \ne \emptyset$ choose the best B agent. If $A^1(t) = \emptyset$, choose $\emptyset$


What are B agents going to do?



$P^1(b) = (\hat{P}^1)^{-1}(\{b\}) \cap A(b) = \{t \in T: \hat{P}^1(t) = b : t \in A(b)\}$


The above means t has made a proposal to me and that t is acceptable to me. 



Now, $\hat{\mu}^1: B \rightarrow T \cup \{\emptyset\}$ such that $\hat{\mu}^1 \in \max_b P^1(b)$


If $P^1(b) = \emptyset$ then $\hat{\mu}^1(b) = \emptyset$. That is if none are acceptable, I hold on to myself


__Round k+1__:


Inductively, I have defined:

- Sets $(A^k(t): t \in T)$
- maps $\hat{P}^k: T \rightarrow B \cup \{\emptyset\}$
- sets $(P^k(b): b \in B)$ and $P^k \subseteq T$
- maps $\hat{\mu}^k: B \rightarrow T \cup \{\emptyset\}$




$A^{k+1}(t) =$ (1) or (2) provided the following conditions:

__(1)__   $A^k(t)$ if $\hat{\mu}^k(\hat{P}^k) = t$ meaning t proposed at k to $b = \hat{P}^k(t)$ and b accepted t at $k$.


But, he if rejected the offer, I throw him out of the running:


__(2)__   $A^k(t) \setminus \{\hat{P}^k(t)\}$ 

if 

$$\hat{\mu}^k(\hat{P}^k(t)) \ne t$$


If I was accepted on round $k$, then I offer the same offer to the same person on round $k+1$. 

$\hat{P}^{k+1}(t) = \hat{P}^k$ if it is the case that  $\hat{P}^k(t) \in A^{k+1}(t)$

$\hat{P}^{k+1}(t) \in \max_t A^{k+1}(t)$ if it is the case $\hat{P}^k(t) \notin A^{k+1}(t)$



The set of proposals that b has on round $k+1$:


$$P^{k+1}(b) = (\hat{P}^{k+1})^{-1} (\{b\}) \cap A(b)$$


Which is equivalent to:

$$\{t \in T: \hat{P}^{k+1}(t) = b: t \in A(b)\}$$










I hold on to exactly the same offer if it is the case that b is still a maximizer for me. 



$$\hat{\mu}^{k+1}: B \rightarrow T \cup \{B\}$$


$\hat{\mu}^{k+1}(b) = \hat{\mu}^{k}(b)$ if it is the case that $\hat{\mu}^{k+1}(b) \in \max_b P^{k+1}(b)$

And

$\hat{\mu}^{k+1}(b) = \max_b P^{k+1}(b)$ if it is the case that $\hat{\mu}^{k+1}(b) \notin \max_b P^{k+1}(b)$



### Lemma 1: the T-proposal in the algorithm terminates:

$$\exists K < \infty: \forall k \ge K: \hat{P}^k = \hat{P}^K \land \hat{\mu}^k = \hat{\mu}^K$$



__Proof__

k is when the acceptable offer stops for every t agent. 

For each $t \in T$, $(A^k(t): k = 1,2,...)$ is decreasing, i.e., $..., \subseteq A^3(t) \subseteq A^2(t) \subseteq A^1(t)$


$$\exists K: \forall t \in T, A^k(t) = A^K(t)$$ 
$$\forall k \ge K$$



By definition, $\hat{P}^k(t) = \hat{P}^K(t)$ for all $t \in T$ and $k \ge K$. This implies that $P^k(b) = P^K(b)$ for all $b \in B$ and $k \ge K$. Which implies that $\hat{\mu}^k(b) = \hat{\mu}^K(b)$ for all $b \in B$ and $k \ge K$. 



This shows that the algorithm terminates. But does it give us a stable match? It is indeed stable by nature of the algorithm. Assuming that each $T$ is a man $m$ and each $B$ is a woman $w$ par Roth and Sotomayor, then:

> To see that the matching $\mu$ produced by the algorithm is stable, suppose some man $m$ and woman $w$ are not married to each other at $\mu$ but $m$ prefers $w$ to his own match at $\mu$. Then, woman $w$ must be acceptable to man $m$, and so he must have proposed to her before proposing to his current mate (or before being rejected by all of the women he finds acceptable). Since he was not engaged to $w$ when the algorithm stopped, he must have been rejected by her in favor of someone she like at least as well. Therefore, $w$ is matched at $\mu$ to a man whom she likes at least as well as man $m$, since preferences are transitive (and hence acyclic), and so $m$ and $w$ do not block the matching $\mu$. Since the matching is not blocked by any individual or by any pair, it is stable. 


### Example


Let $T = \{t_1, t_3, t_3\}$ and also $B = \{b_1, b_2, b_3\}$

$$t_1: b_2 \succ_{t_1} b_1 \succ_{t_1} b_3 \succ_{t_1} t_1$$
$$t_2: b_1 \succ_{t_2} b_2 \succ_{t_2} b_3 \succ_{t_2} t_2$$
$$t_3: b_1 \succ_{t_3} b_2 \succ_{t_3} b_3 \succ_{t_3} t_3$$



Notice $t_2$ and $t_3$ have the same preferences. 


$B$'s preferences:

$$b_1: t_1 \succ_{b_1} t_3 \succ_{b_1} t_2 \succ_{b_1} b_1$$
$$b_2: t_2 \succ_{b_2} t_1 \succ_{b_2} t_3 \succ_{b_2} b_2$$
$$b_3: t_1 \succ_{b_3} t_3 \succ_{b_3} t_2 \succ_{b_3} b_3$$




Notice $b_1$ and $b_3$ have the same preference.




__Step 1:__

- for all $t \in T: A^1(t) = B$
- $\hat{P^1}(t_1) = b_2, \hat{P}^1(t_2) = b_1, \hat{P}^1(t_3) = b_1$
- $P^1(b_1) = \{t_2, t_3\}$ and $P^1(b_2) = \{t_1\}$ and $P^1(b_3) = \emptyset$
- $\hat{\mu}^1(b_1) = t_3$ and $\hat{\mu}^1(b_2) = t_1$ and $\hat{\mu}^1(b_3) = \emptyset$



__Step 2:__

- $A^2(t_1) = B$ and $A^2(t_2) = \{b_2, b_3\}$ and $A^2(t_3) = B$
- $\hat{P}^2(t_1) = b_2$ and $\hat{P}^2(t_2) = b_2$ and $\hat{P}^2(t_3) = b_1$
- $P^2(b_1) = \{t_3\}$ and $P^2(b_2) = \{t_1, t_2\}$ and $P^3(b_3) = \emptyset$
- $\hat{\mu}^2(b_1) = t_3$ and $\hat{\mu}^2(b_2) = t_2$ and $\hat{\mu}^2(b_3) = \emptyset$



__Step 3:__

- $A^3(t_1) = \{b_1, b_3\}$ and $A^3(t_2) = \{b_2, b_3\}$ and $A^3(t_3) = B$
- $\hat{P}^3(t_1) = b_1$ and $\hat{P}^3(t_2) = b_2$ and $\hat{P}^3(t_3) = b_1$
- $P^3(b_1) = \{t_1, t_3\}$ and $P^3(b_2) = \{t_2\}$ and $P^3(b_3) = \emptyset$
- $\hat{\mu}^3(b_1) = t_3$ and $\hat{\mu}^3(b_2) = t_2$ and $\hat{\mu}^3(b_3) = \emptyset$



__Step 4:__

- $A^4(t_1) = \{b_1, b_3\}$ and $A^4(t_2) = \{b_2, b_3\}$ and $A^4(t_3) = \{b_2, b_3\}$
- $\hat{P}^4(t_1) = b_1$ and $\hat{P}^4(t_2) = b_2$ and $\hat{P}^4(t_3) = b_2$
- $P^4(b_1) = \{t_1\}$ and $P^4(b_2) = \{t_2, t_3\}$ and $P^4(b_3) = \emptyset$
- $\hat{\mu}^4(b_1) = t_1$ and $\hat{\mu}^4(b_2) = t_2$ and $\hat{\mu}^4(b_3) = \emptyset$



__Step 5:__

- $A^5(t_1) = \{b_1, b_3\}$ and $A^5(t_2) = \{b_2, b_3\}$ and $A^5(t_3) = \{b_3\}$
- $\hat{P}^5(t_1) = b_1$ and $\hat{P}^5(t_2) = b_2$ and $\hat{P}^5(t_3) = b_3$
- $P^5(b_1) = \{t_1\}$ and $P^5(b_2) = \{t_2\}$ and $P^5(b_3) = \{t_3\}$
- $\hat{\mu}^5(b_1) = t_1$ and $\hat{\mu}^5(b_2) = t_2$ and $\hat{\mu}^5(b_3) = t_3$.




You can check this is exactly what was completed last class without the Differed Acceptance Algorithm. 

Since it terminates at $k+1$ technically there is a __Step 6__ where everything in __5__ is repeated. 









































