---
title: "Lecture 2"
author: "David Zynda"
date: "August 23, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matching Environment
Let the enviroment $\epsilon$ be defined as:

$$\epsilon = (T, B; (\succsim_i)_{i \in T \cup B})$$

So, $\succsim_t$ is the binary relation on $B \cup \{t\}$ and $\succsim_b$ is the binary relation on $T \cup \{t\}$.

We add to environment, as in last lecture, a matching represented by:

$$\mu: (T \cup B) \rightarrow (T \cup B)$$

such that:

1. for each $i \in I: \mu(i) \in J \cup \{i\}$

2. if $\mu(i) = j \in J$ then $\mu(j) = i \in I$.


Now, what cases would individuals or groups of individuals have the incentive to deviate from the match they have? In other words, is that match suitable?





## Acceptable Matches


__Definition__: A match is acceptable if an agent prefers a match rather than being alone. Formally, $j \in J$ is acceptable to $i \in I$ if $j \succsim_i i$. Or:

$$A(i) = \{j \in J: j \succsim_i i\}$$


This simply says that "I like $j$ at least as much as I like being alone". 




__Definition__: A matching is _individually rational_ (IR) if for each side of the market $I \in \{T,B\}$ and each $i \in I$:
$$\mu(i) \in A(i) \cup \{i\}$$




__Definition__: a pair $(t,b)$ blocks $\mu$ if:


-  $b \succ_t \mu(t)$
-  $t \succ_b \mu(b)$


In English:

-  $t$ prefers $b$ to whoever he is matched with. 
-  $b$ prefers $t$ to whoever he is matched with. 



__Definition__: a match $\mu: (T \cup B) \rightarrow (T \cup B)$ is suitable if it is individually rational (IR) and there is no blocking pair. 





## Example 1:

Imagine an environment with, say, two firms $T$ and two employees $B$:


$T = \{t_1, t_2\}$

$B = \{b_1, b_2\}$


Preferences of $T$:


$$t_1: \space b_1 \succ_{t_1} b_2 \succ_{t_1} t_1$$

$$t_2: \space b_2 \succ_{t_2} b_1 \succ_{t_2} t_2$$


Preferences of $B$:


$$b_1: \space t_2 \succ_{b_1} t_1 \succ_{b_1} b_1$$

$$b_2: \space t_1 \succ_{b_2} t_2 \succ_{b_2} b_2$$


_Note: these lecture notes are bound to have mistakes. Pay close attention to where I may have put $\succsim$ instead of $\succ$ I think I have corrected them all in this lecture_

As can be seen, each match is individually rational since for each individual in each side of the market, they either prefer to keep to themselves or has an agent on the otherside of the market who is at least as much preferred than to be alone. 


Let's examine 3 cases and see if there is a suitable match, or if a blocking pair stands in the way:

1. $\mu(t_1) = b_2$
2. $\mu(t_1) = b_1$
3. $\mu(t_1) = t_1$




__Case 1:__ $\mu(t_1) = b_2$


$\mu(t_1) = b_2 \implies \mu(b_2) = t_1$


This implies (by "no blocking pair") that $\mu(b_1) = t_2 \implies \mu(t_2) = b_1$

In short: 

$$\mu(t_1) = b_2$$ 
$$\mu(b_1) = t_2$$ 
$$\mu(t_2) = b_1$$
$$\mu(b_2) = t_1$$

are all stable matchings. Here, every $b$ gets its most preferred option


__Case 2:__ $\mu(t_1) = b_1$

$\mu(t_1) = b_1 \implies \mu(b_1) = t_1$

This implies by "no blocking pair" that $\mu(t_2) = b_2 \implies \mu(b_2) = t_2$

Since there is no blocking pair, all the matches are stable. Every $t$ gets their most preferred option. 


__Case 3:__ $\mu(t_1) = t_1$

If $\mu(t_1) = t_1$ then $\exists b \in B$ with $\mu(b) = b$. Then $(t_1, b)$ forms a blocking pair. This matching is not stable. 



## Lemma

Suppose all agents have strict preferences and:

$$|\{t \in T: A(t) = B\}| = |\{b \in B: A(b) = T\}| = k.$$

In English, the number in the set of all $t$'s who find all $b$'s acceptable is equal to the number in the set of all $b$'s who find all $t$'s acceptable is set to the value of $k$


Then, if $\mu : (T \cup B) \rightarrow (T \cup B)$ is stable, then:

$$|\{t \in T: \mu(t) \ne t\}| \ge k$$


Again, in English the set of $t$ agents matched has to contain at least $k$ elements. For example, say that there are 20 $t$'s and 30 $b$'s. If 10 $b$'s find all $t$'s acceptable and vice versa, then the number of stable matchings is at least 10. 


### Proof: 
Suppose the the contrary that:

__IF__ (the same as the original antecedent)

$$|\{t \in T: A(t) = B\}| = |\{b \in B: A(b) = T\}| = k.$$
and if $\mu : (T \cup B) \rightarrow (T \cup B)$ is stable

__THEN__ (The negation of the consequent)
$$\{t \in T: \mu(t) \ne t\}| < k$$


Assuming this, if follow that:
$$\exists t \in T : \mu(t) = t$$

However, since the number of $t$'s is less than all possible stable matchings $k$ (as there exists one $t$ who matches with itself), it follows that:

$$\exists b \in B : \mu(b) = b$$

It would then have to be the case there is a pair $(t, b)$ which blocks $\mu$. This is a contradiction, since we assumed $\mu$ was stable





### Corollary

Suppose $|T| = |B|$ and for each agent $i$:

1. $i$ has strict preferences
2. $A(i) = J$

Then, in a stable match, all agents are matched. 


## Example 2

$$T = \{t_1, t_2, t_3\}$$
$$B = \{b_1, b_2, b_3\}$$


$T$'s preferences:

$$t_1: b_2 \succ_{t_1} b_1 \succ_{t_1} b_3 \succ_{t_1} t_1$$
$$t_2: b_1 \succ_{t_2} b_2 \succ_{t_2} b_3 \succ_{t_2} t_2$$
$$t_3: b_1 \succ_{t_3} b_2 \succ_{t_3} b_3 \succ_{t_3} t_3$$



Notice $t_2$ and $t_3$ have the same preferences. 


$B$'s preferences:

$$b_1: t_1 \succ_{b_1} t_3 \succ_{b_1} t_2 \succ_{b_1} b_1$$
$$b_2: t_2 \succ_{b_2} t_1 \succ_{b_2} t_3 \succ_{b_2} b_2$$
$$b_3: t_1 \succ_{b_3} t_3 \succ_{b_3} t_2 \succ_{b_3} b_3$$




Notice $b_1$ and $b_3$ have the same preference. 



Also notice that $|T| = |B|$ and $A(t) = B$ and $A(b) = T$. 

Then, by the corollary, in a stable match, all agents are matched!

Once again, let's consider three possible matchings:

1. $\mu(t_1) = b_2$
2. $\mu(t_1) = b_1$
3. $\mu(t_1) = b_3$



__Case 1:__ $\mu(t_1) = b_2$

$$\mu(t_1) = b_2 \implies \mu(b_2) = t_1$$

By "no blocking pair", this means that $\mu(t_2) = b_1 \implies \mu(b_1) = t_2$

And again, $\mu(t_3) = b_3$

Now, $(t_3, b_1)$ form a blocking pair. So, this matching is not stable. 

$$b_1 \succ_{t_3} t_3$$ 
$$\mu(t_3) = b_3$$
$$t_3 \succ_{b_1} b_1$$ 
$$\mu(b_1) = t_2$$


Conclusion: if $\mu$ is stable, then $\mu(t_1) = b_1$




__Case 2:__ $\mu(t_1) = b_1 \implies \mu(b1) = t_1$

We can infer (by no blocking pair) that:

$$\mu(b_2) = t_2 \implies \mu(t_2) = b_2$$
$$\mu(t_3) = b_3 \implies \mu(b_3) = t_3$$

There is no blocking pair because $b_1$ and $b_2$ are geting their best. This is stable (and it fulfills the corollary)



__Case 3:__ $\mu(t_1) = b_3 \implies \mu(b_1) \ne t_1$

Now:

$$t_1 \succ_{b_1} \mu(b_1) = t_2$$
$$b_1 \succ_{t_1} \mu(t_1) = b_3$$

Hence there is a blocking pair. If matching is stable, then $\mu(t_1) \ne b_3$. 














