---
title: "Econ 501A HW 3"
author: "David Zynda"
date: "September 12, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Problem 3.6

_(a) Suppose that $\mathcal{B}$ contains all duos. Consider two preferences $\succsim$ and $\succsim'$ and the choice rules $C_{\succsim}$ and $C_{\succsim'}$. Consider the two following conditions: (i) for each pair of alternatives $x,y \in X$, $x \succsim y \iff x \succsim' y$ and (ii) for each budget set $B \in \mathcal{B}$ $C_{\succsim}(B) = C_{\succsim'}(B)$. Prove that (i) $\iff$ (ii)._



First, assume (i) $\implies$ (ii). 

$C_{\succsim}(B)$ is a choice rule generated by the preference $\succsim$. Specifically:
$$C_{\succsim}(B) = \{x \in \mathcal{B} : x \succsim y, \forall y \in \mathcal{B}\}$$

On the likewise: 
$$C_{\succsim'}(B) = \{x \in \mathcal{B} : x \succsim' y, \forall y \in \mathcal{B}\}$$
Since $x \succsim y \iff x \succsim' y$ and if $C_{\succsim}(B) =  \{x\}$ then $C_{\succsim'}(B) = \{x\}$. Therefore, $C_{\succsim}(B) = C_{\succsim'}(B)$

Now, assume (ii) $\implies$ (i). 

We know $C_{\succsim}(B) = C_{\succsim'}(B) = S$. Because $C_{\succsim}(B)$. It must be the case for any duo $x,y \in B$ that  $s = \{x\}$. So, the choice rule is finite nonempty and fulfills the weak axiom of revealed preferene. Then, its preference representation exists. In fact, given the set $S$, we know that $x \succsim y$ and not $y \succsim x$. Now, we assumed $C_{\succsim}(B) = C_{\succsim'}(B) = S$. Therefore, $\succsim'$ also exists and is equivalent to $\succsim$. 


_______________________________________________________________

_(b) Again, suppose that $\mathcal{B}$ contains all duos. Consider a preference $\succsim$ a utility function $u$, and the resulting choice rules $C_{\succsim}$ and $C_u$. Prove that $u$ represents $\succsim$ if and only if $C_{\succsim}(B) = C_u(B)$ for all $B \in \mathcal{B}$_



Let:
$$C_{\succsim}(B) = \{x \in X : x \succsim y, \forall x,y \in X\}$$
$$C_{u}(B) = \{x \in X : u(x) \ge u(y), \forall x,y \in X\}$$

First, assume $C_{\succsim}(B) = C_u(B)$. We know that $C_{\succsim}(B) = C_u(B) = \{x\}$ since the choice rule is defined to choose the set of $x \in B$ where $x \succsim y$ and $u(x) \ge u(y)$ respectively. Then, it does not exclude choosing the duo entirely. Now, with this result, we know that $C_{\succsim}$ satisfies choice coherence (weak axiom) and finite nonemptiness. Hence, there is a unique complete and transitive preference that represented by the choice rule. Now, we also assumed $C_{\succsim}(B) = C_u(B)$. So, $C_u(B)$ also has a complete and transitive preference relation that is unique (see Asaf's notes Proposition 3.3). So, the preference relations are the same. And $C_u(B)$ is generated by $u$. Therefore, $C_{\succsim}(B) = C_u(B) \implies u$ represents $\succsim$. 


Second, assume we know that $\succsim$ represents $u$. Because of this, $\succsim$ generates a nonempty and coherent choice rule $C_{\succsim}(B)$. And, $u$ is also complete and transitive, so $C_u(B)$ is also a nonempty and coherent choice rule. Then, $C_{\succsim}(B) =  \{x\} = C_u(B)$ for any duo $x,y \in B$. 

_______________________________________________________________
 
_(c) Now relax the assumption that $\mathcal{B}$ contains all duos. Does the claim in part (a) continue to hold? If so, prove it. If not, provide a counter example, and explain whatever parts of the claim continue to hold._



Assume that $\mathcal{B}$ contains all duos except $(x,z)$. That is, assume for $\{x,y,z\}$: $\{x,y\},\{y,z\} \in \mathcal{B}$. Then assume:

$$C_{\succsim}(x,y) = \{x\} = C_{\succsim'}(x,y)$$
$$C_{\succsim}(y,z) = \{z\} = C_{\succsim'}(y,z)$$
$$C_{\succsim}(x,z) = \{\emptyset\} = C_{\succsim'}(x,z)$$

And hence:



$$x \succsim y \iff x \succsim' y$$
$$z \succsim y \iff z \succsim' y$$
$$z \succsim x \not\implies x \succsim' z$$

_______________________________________________________________


_(d) Continue to relax the assumption that $\mathcal{B}$ contains all duos. Does the claim in part (b) continue to hold? If so, prove it. If not, provide a counter example, and explain whatever parts of the claim continue to hold. _


It is true the (i) $\implies$ (ii) when the condition is relaxed. If $u$ represents $\succsim$, then $\succsim$ is complete and transitive for whatever set $B \in \mathcal{B}$. Since $u$ assigns real numbers to $B$, $u$ is complete and transitive and thus $\succsim$ inherits those qualities, for any finite set of numbers that may not only be duos. Then, because both $u$ and $\succsim$ are complete and transitive, they have coherent choice rules that satisfy finite nonemptiness $C_u(B)$ and $C_{\succsim}$. Because they both satisfy choice coherence, it must be the case that the choice rules are the same. 


(ii) $\implies$ (i) does not hold. 

Assume that $\mathcal{B}$ contains all duos except $(x,z)$. That is, assume for $\{x,y,z\}$, $\{x,y\},\{y,z\} \in \mathcal{B}$. Then assume:

$$C_{\succsim}(x,y) = \{x\} = C_{u}(x,y)$$
$$C_{\succsim}(y,z) = \{z\} = C_{u}(y,z)$$
$$C_{\succsim}(x,z) = \{\emptyset\} = C_{u}(x,z)$$

And hence:



$$x \succsim y \iff u(x) \ge u(y)$$
$$z \succsim y \iff u(z) \ge u(y)$$
$$z \succsim x \not\implies u(x) \ge u(z)$$


## Problem 3.7

Like the finite case, a preference $\succsim$ still has a utility representation if and only if it is complete and transitive in a countably infinite environment. If uncountably infinite, one will need continuity. Presumably, countably infinite numbers can still be compared in such away as to guarantee complete and transitive properties. However, the case might not be so clear for the choice rule. Under the finite case, a choice structure is rationalizable if and only if it satisfies the weak axiom and it is also finitely nonempty. So, the condition of finite nonemptiness no longer holds, and the bridge linking choice to preference seems a bit less clear. However, the weak axiom may still be okay and sensible since it is fundamentally rooted in choice consistency. 






## Problem 4.1


_(a) Prove that the budget set $B(p,w)$ has the properties listed in the previous proposition (except convexity)_

(i) The set $B$ is nonempty since it contains the zero vector.

(ii) The set is compact because it is both closed and bounded. 

>Because $B(p, w)$ denotes the budget set, let $b(x, \varepsilon)$ denote the $\epsilon$-ball around $x$. 

>First, assume that the set is open. Then, $\forall x \in B$, $\exists b(x, \varepsilon)$ such that $b(x, \varepsilon) \subset B$. This implies that there exists a point $x_0$ along the budget line (plane) $px_0 = w$ where $B(x_0, \varepsilon) \subset B$. But, this cannot be since for any $\varepsilon > 0$, the income $w$ would be exceeded by $\varepsilon$. Therefore, the set is not open. So, the set is closed. 

>By definition, the set is bounded below since $B(p,w) = \{x \in \mathbb{R}_+^k : px \le w\}$ Here, any element $x \in B(p,w)$ cannot be anything less than $0$ since it is defined nonnegative. It also must be bounded above too, by the same definition. Notice that $x \in B$ cannot exceed $w$, the dot product of $p$ and $x$. Therefore, it is also bounded from above by the line or plane $px = w$. 

(iii) The set is the intersection of $k+1$ closed half spaces. Assume that $B(p,w) = \{x \in \mathbb{R}_+^2 : px \le w\}$. Then, the set is the intersection of $k + 1 = 3$ closed half spaces. First, the set includes everything on and below the budget plane $p \cdot x = w$. This is a closed half space since $\forall x': px = w$ the space includes $(-\infty, x']$. 

>Because we define $x \in \mathbb{R}^2_+$, we know that no quantity of $(x_1, x_2)$ can be negative. Therefore, we have two closed half spaces $[(0, x_2), \infty)$ and $[(x_1, 0), \infty)$. 

>So, one half space representing the budget place put a bound above the set. Two planes put a bound below the set at $x_1 = 0$ and $x_2 = 0$. The space contained within this region then represents the intersection of 3 closed half spaces. 


_(b) The expression "$++$" in the expression $p \in \mathbb{R}^k_{++}$ indicates that the price of each of the $k$ goods is strictly greater than zero. What if instead we assume only that the price of each good is greater than or equal to zero, that is $p \in \mathbb{R}^k_+$. Which of the four previously established properties of $B(p,w)$ must continue to hold?_

(i) The set will still be nonempty because it will still contain at least the zero vector. 

(ii) The set will still be convex. The proof provided in the notes still stands:

>Let $x^0, x^1 \in B(p,w)$ and let $t \in [0,1]$. Since $px^0 \le w$ and $px^1 \le w$ for any $p$ including the case $p \in \mathbb{R}^k_+$ where $p = 0$, the statement is still true. So, for $x^t = tx^1 + (1-t)x^0$, 

$$px^t \le ptx_1 + p(1-t)x^0 \le tw + (1-t)w \le w$$

>And, $x_i^0 \ge 0$ and also $x_i^t \ge 0$. So, including prices that can take on the value of zero do not affect the convexity assumption. 


(iii) The set is no longer compact because it is not bounded. For any good $x \in B(p,w)$ If it is the case that $p$ is the zero vector, Then any quantity of $x$ desired by the consumer can be had under his contraint $w$. 


(iv) The set cannot be the intersection of closed half spaces. Assume that prices for all goods in the price vector are zero. Also, assume that there are two goods, such that $k=2$. Then, the space is still has two closed half spaces since we have the assumption that the consumer cannot consume negative quantities of goods, but could consume zero (hence bounded by $x1 = 0$ and $x_2 = 0$.) But, now it is not bounded above, but the set $B(0,w) = \mathbb{R}^2_+$. Hence, the set will no longer be the intersection of $k+1 = 3$ half spaces. 




_(c) Suppose we dispose with the nonnegativity constraint, so instead we define $B(p,w) = \{x \in \mathbb{R}^k : px \le w\}$ for some $p \in \mathbb{R}^k_{++}$ and $w \in \mathbb{R}_+$. Which of the four previously established properties of $B(p,w)$ must continue to hold? Prove your answer._


(i) The set is still nonempty. It still contains at least the zero vector. 

(ii) The set is still convex. let $x^0, x^1$ be two different bundles in $B(p,w)$. Note that $-\infty < x^0 < \infty$ and $-\infty < x^1 < \infty$ in theory, but both will be subject to $w$. Let $t \in [0,1]$ and $x^t = tx^1 + (1-t)x^0$. Then, we know that

$$px^t \le ptx_1 + p(1-t)x^0 \le tw + (1-t)w \le w$$

>If $x^0, x^1 < 0$ then, any linear combination with $t$ will still be less than $w$ and so it will still be in the set. Therefore, the set defined by $B(p,w) = \{x \in \mathbb{R}^k : px \le w\}$ is still convex. 

(iii) The set is not compact because it is not bounded. 

>Assume that $B(p,w)$ is bounded below by $L$. Then, $\forall \varepsilon > 0: \exists L \in \mathbb{R}^k : \forall x \in B(p,w): x \ge L$

>But, suppose the consumer can consume less than $L$ since for any $M < L: M \in B(p,w)$ since $M$ is still under the budget constraint and $x \in \mathbb{R}^k$. Let $x = M$. Then, $x < L$. So, the set is unbounded, and cannot be compact. 



(iv) The set is no longer the intersection of $k+1$ half spaces. Consider part (iii) above. Since there is no greatest lower bound, there is no plane to divide the space. There is still the budget $p \cdot x \le w$. But this is one half space, not $k+1$. 


 