---
title: "Econ 501A HW 2"
author: "David Zynda"
date: "September 5, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Problem 2.3

_If $\succeq$ is a complete and trasitive preference on a finite set $X$, then $\succeq$ has a utility representation_



Let $X$ be a finite set with $\succeq$ as a complete and transitive preference on the set. Then, define subsets of $X$ for each element $x \in X$ such that:

$$W(x) = \{y \in X: x \succeq y\}$$
If $X$ is finite with a complete and transitive preference relation, that means there will be a $W(x)$ since either $x \succeq y$ or $y \succeq x$ which implies $W(x) = y$ or $W(y) = x$. This works as well if $X$ is a singleton since $x \succeq x \implies W(x) = x$. In other words $W(x)$ is nonempty and complete. 

For transitivity, as usual let $x \succeq y$ and $y \succeq z$. Because the preference is transitive, then: $x \succeq z$. Also allow for $z \succeq t$, such that by transitivity $x \succeq t$. This implies, by definition of $W(x)$ that: $W(x) = y$, $W(y) = z$, $W(z) = t$ Then, $W(x) \succeq W(y) \succeq W(z)$. 

Then for each element in the set $X$, $W(x)$ returns a set containing all the elements that are as preferred to $x$ and not as preferred to $x$. 

Define a function $u(x): W(x) \subseteq X \rightarrow \mathbb{R}$. Let $u(x)$ return a real number representing the number of elements in $W(x) \subseteq X$. 

Let $u(x) = a$ and $u(y) = b$. Assume $x \succeq y$, and therefore the number of elements in $u(x) = a$ will either contain the same number of elements as $u(b)$ or more. In other notation, $u(x) = a \ge u(y) = b$. Therefore, 

$$x \succeq y \implies u(x) \ge u(y)$$


Now, assume that $u: W(x) \subset X \rightarrow \mathbb{R}$ takes two subsets of $X$, $W(A)$ and $W(B)$. By definition of $W(x)$, one set is a subset of the other. Assume $A \subseteq B$. Will a preference relation exists between them? Since $A \subset B$, either $A$ has as many elements of $B$ or less. Therefore, $u(A) = W(A) \le u(B) = W(B)$. Therefore $\forall a \in A$ and $\forall b \in B: b \succeq a$. But, it could also be the case that $B \subseteq A$. Then, $a \succeq b$. Therefore, there is a complete preference relation implied by $u(x)$. 

Now, assume there are three sets in $X$ generated by $W(x): C \subseteq B \subseteq A$. Then, $u(C) \le u(B)$ and $u(B) \le u(A)$. Therefore, $u(C) \le u(A)$. Then, for any $a \in A$, $b \in B$, and $c \in C$, transitivity holds as well for $\succeq$. 


## Problem 3.1

_Prove: If $\succeq$ is complete, and $B$ containts just two elements then $C_\succeq(B)$ is nonempty. Conversely, if $\succeq$ is not complete, there exists some $B \subset X$ containing just two elements such that $C_\succeq(B)$ is empty. If $\succeq$ is complete and transitive, $\mathcal{B}$ and $C_{\succeq}$ satisfies finite nonemptiness_

(a) Let $B$ be a set containing two elements $a, b$. Since $\succeq$ is complete and transitive, either: $a \succeq b$ or $b \succeq a$. 

If $a \succeq b$, then $C_{\succeq}(B) = \{a\}$. But, if $b \succeq a$, then $C_{\succeq}(B) = \{b\}$. In either case, $C_{\succeq}(B)$ is nonempty. 


(b) There are three cases to consider. First, assume $B \subseteq \mathcal{B}$. By definition, the set of budget sets $\mathcal{B} \subset X$ for $X$ grandset of all alternatives, $\mathcal{B}$ is assumed to be nonempty. Therefore, $B \subseteq \mathcal{B}$ is nonempty. 

The first case to consider is that $B$ is a singleton. That is, $B$ has one element $b$. Then, we know $C_{\succeq}(B) = \{b\}$ and thus nonempty. 

The second case is that $B$ has two members in its set, say $a, b$. Part (a) of this problem already shows that such a case is nonempty. 

The final case is that $B$ has three or more elements. Since $\succeq$ is complete, for any $a, b \in B$, $a \succeq b$ or $b \succeq a$. And if we also consider a $c \in B$ such that $a \succeq b$ and $b \succeq c$, then $a \succeq c$. In fact, there will be one alternative, presumably that is more preferable than all others in $B$ because of transitivity. Call this element $a$. There could be more, but it is sufficient to assume one since then:

$$C_{\succeq}(B) = \{a\}$$.


Therefore, $\mathcal{B}, C_{\succeq}(B)$ satisfies finite nonemptiness. 


## Problem 3.2

Suppose that $X$ is finite. Consider a choice rule $C(\cdot)$ defined on all nonempty subsets of $X$. There exists a complete and transitive preference that generates the choice rule $C(\cdot)$ if and only if $C(\cdot)$ satisfies the weak axiom of revealed preference and $C(B)$ is nonempty for all nonempty $B \subset X$. 

We assumed that $C(\cdot)$ is defined on all nonempty subsets of $X$. Therefore, finite nonemptiness is satisfied. Then, let $x,y \in B$. Either $x \in C(B)$ or $y \in C(B)$. Therefore, the preference represented by $C(B)$, $\succsim$ is complete since $x \succsim y$ or $y \succsim x$. 

Let $z$ also be in $B$. Also, assume that $x \in C(B)$. In other terms, $x \in C(\{x,y,z\})$. This means $x \succsim y$ and $x \succsim z$. So, if $y \in C(B)$, then it must be the case that $x \notin B$ or else the choice would not be coherent or rational (that the weak axiom is fulfilled). Consequently, it must be the case that for a set $B' = \{x,y\}$, $C(B') = x$. Then $x \succsim y$. Similarly, $C(\{y,z\}) = y$ means that $y \succsim z$. Therefore, we have transitivity of our preference $\succsim$. 


If $\succsim$ is complete and transitive, it must be the case that the weak axiom is fulfilled and the choice rule fulfills finite nonemptiness. 

If the preference is complete, this means that $x \in C(B)$ or $y \in C(B)$. If there is only one element $x \in B$, it is still complete since $x \succsim x \implies x \in C(B)$ or $x \in C(B)$ Either way, the choice satisfies finite nonemptiness. 

Now, suppose that $x \succsim y$ and $y \succsim z$ for $x,y,z \in B$. By transitivity, we know that $x \succsim z$. Now, $x \in C(B)$. If, $B' = \{x,y\}$, then $x \in C(B')$ and if $B'' = \{y,z\}$, then $y \in C(B'')$. Therefore, transitivity implies that the weak axiom is satisfied and the proof is complete. 


## Problem 3.3

_(a) Ann chooses the cheapest bottle._

Ann always chooses the cheapest wine bottle. That is $\forall B = \{x_1,...,x_n\}$ she chooses $\min x_i$ for $i = 1,2,...,n$. If $B = {x}$ then she chooses $x$.  

Assume that Ann's $\mathcal{B}$ contains all subsets $B$ of 3 wine selections since $\mathcal{B} = \mathcal{P}(X) \setminus \emptyset$. Let one such $B = \{x_1, x_2, x_3\}$. Then, between $x_1$ and $x_2$, she chooses $x_1$. Between $x_2$ and $x_3$ she chooses $x_2$. And between $x_1$ and $x_3$, she chooses $x_1$. Then, the weak axiom is satisfied because she always chooses $x_1$ when it is contained in the budget set of alternatives. That is, there is never a time when she chooses $x_1$ and then does not choose $x_1$ when $x_1$ is included in the set. 

If ($\mathcal{B}, C(\cdot)$) is a choice structure such that the weak axiom is satisfied and $\mathcal{B}$ includes all subsets of $X$ of up to three elements, then there is guaranteed to be a rational preference relation that rationalizes $C$ relative to $\mathcal{B}$ and it is the only one. 

We can also see that the choices among $B$ are complete. Either $x_i \succeq x_j$ or $x_j \succeq x_i$ for all $i,j = [1,3]$ the set of natural numbers from $1$ to $3$. Also, transitivity is maintained: $x_1 \succeq x_2$ and $x_2 \succeq x_3$ implies $x_1 \succeq x_3$. 

Even if there were more than three elements this would still be true. Adding another $x_i$ will result in the new addition being cheaper than the lowest price wine of the set or more. If it is cheaper, she chooses that one. If it is more expensive, she does not, and it falls before the first $j^{th}$ bottle of wine that is more expensive than it. Even so, transitivity and completeness is maintained either way. 

_(b) Bob chooses the second cheapest bottle._ 

Although the weak axiom is not sufficient to guarantee a choice is rationalizable, it can be a testament against it. Of Bob's selections of wine, he always chooses the second cheapest bottle. Assume he has three bottles to choose from:

$$X = \{x_1, x_2, x_3\}$$
And the price of $x_1$ is less than the price of $x_2$ and the price of $x_2$ is less that the price of $x_3$. Then, the price of $x_1$ is also less than the price of $x_3$. Now, let $B_i$ be an $i^{th}$ subset of B:

$$B_1 = \{x_1, x_2\}$$
$$B_2 = \{x_2, x_3\}$$
$$B_3 = \{x_1, x_3\}$$
This implies that the choice of each of the sets will be as follows:

$$C(B_1) = \{x_2\}$$
$$C(B_2) = \{x_3\}$$
$$C(B_3) = \{x_3\}$$

But when $B$ contains all three options: $C(B) = \{x_2\}$. So, there is a set containing ${x_2, x_3}$ where $x_3$ is not choosen, in spite of $C(B_2)$ above. Therefore, the weak axiom is violated. This is not a rationalizable preference. 

(c) ########################!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!################

## Problem 3.4

_Show that a choice structure $(\mathcal{B}, C(\cdot)$) for which a rationalize preference relation $\succeq$ exists satisfies the path-invariant property: For every pair $B_1, B_2 \in  \mathcal{B}$, such that $B_1 \cup B_2 \in \mathcal{B}$, and $C(B_1) \cup C(B_2) \in \mathcal{B}$, we have $C(B_1 \cup B_2) = C(C(B_1) \cup C(B_2))$, that is the division problem can safely be divided._ 


It is assumed that the choice structure is rationalized. Therefore, we know that the weak axiom holds, and that $\mathcal{B}$ contains all subsets of $X$ of up to 3 elements. Thus, by Proposition 1.D.2 in MWG, we can specify the following:

Let $B = \{x, y, z\}$ and $x \succsim y$, $y \succsim z$ and $x \succsim z$. Let $B_1 = \{x,y\}$ and $B_2 = \{y,z\}$. 

$$C(B) = C(\{x,y,z\}) = \{x\}$$
$$C(B_1) = C(\{x,y\}) = \{x\}$$
$$C(B_2) = C(\{y,z\}) = \{y\}$$

This implies that $$C(B_1 \cup B_2) = C(\{x,y\} \cup \{y,z\}) = \{x\}$$

Then, we know that:

$$C(B_1 \cup B_2) = C(\{x,y\} \cup \{y,z\}) = C(\{x\} \cup \{y\} \cup \{y\} \cup \{z\}) = C(\{x\} \cup \{y\} \cup \{z\}) = \{x\}$$

$$C(\{x\} \cup \{y\} \cup \{z\}) = \{x\} = C(\{x\} \cup \{y\})$$
We know from above that: $C(B_1) = \{x\}$ and $C(B_2) = \{y\}$. Therefore:

$$C(\{x\} \cup \{y\}) = C(C(B_1) \cup C(B_2))$$


## Problem 3.5

_Consider a single-valued choice rule, that is a choice rule where $C(B)$ consists of a single element $c(B)$ for each budget set $B$. Show that the following three conditions are equivalent, i.e., each of these three conditions implies the other two( $(i) \implies (ii),(ii) \implies (iii)$ and $(iii) \implies (i)$)_

$(i) \implies (ii)$:

_If the single-valued choice rule $c(\cdot)$ satisfies the weak axiom of revealed preference, then given two budget sets $B$ and $B'$ which each contain the pair of distinct elements x and y, if $c(B) = x$ then $c(B') \ne y$._

Assume that given two budget sets $B$ and $B'$ which each contain the pair of distinct elements $x$ and $y$, if $c(B) = x$, then also $c(B') = y$. 

With this assumption, these two budget sets contain in common two elements where only one is chosen for one budget set and another is chosen for the other. The weak axiom of revealed preference holds that if two pairs of alternatives $a,b$ are present in two different budget sets $B_1, B_2$, then if $a \in C(B_1)$ and $b \in C(B_2)$ then it must be the case also that $a \in C(B_2)$. 

However, because this problem restricts to single-valued choice rules, $c(B') \ne x$ since $c(B') = y$. Therefore, the single valued choice rule does not satisfy the weak axiom of revealed preference and the proof by contraposition is complete. 

___________________________________________________________________________

$(ii) \implies (iii)$:

_Given two budget sets $B$ and $B'$ which each contain the pair of distinct elements x and y, if $c(B) = x$ then $c(B') \ne y$ implies that if $B$ contains $x$ and $y$, $c(B) = x$ and $c(B') = y$, then $x \notin B'$._


Although these statements are equivalent, in the parlance of (ii) implies (iii), they contradict one another since the first assumes the $B$ and $B'$ both have a pair of distinct elements, and the second one says that they do not. So, then, lets suppose (ii) is correct. 

It was shown that (i) is equivalent to (ii). That is, (ii) abides by the weakness axiom. So, if there were a case where $c(B) = x$ and $c(B') = y$, then it would have to be the case that $x \not B'$ or else the weakness axiom would be violated since $c(B')$ is a single-valued choice rule. So, given that a sufficient condition is that (ii) abides by the weakness axiom, (iii) is also implied in the case that $c(B') = y$.

______________________________________________________________________________

$(iii) \implies (i)$

_Given two budget sets $B$ and $B'$ if $c(B) = x$ then $c(B') \ne y$ implies that if $B$ contains $x$ and $y$, $c(B) = x$ and $c(B') = y$, then $x \notin B'$ implies that the single-valued choice rule $c(\cdot)$ satisfies the weak axiom of revealed preference._



Assume the single single-valued choice rule $c(\cdot)$ does not satisfy the weak axiom of revealed preference.

Let $B$ contain $x, y$ such that $c(B) = x$. Now, $c(B)$ and $c(B')$ are of course single-valued choice rules admitting of only a single element. So that we are consistent with the assumption that the weakness axiom is not satisfied, it would have to be the case that $c(B') = y$ and that both $x,y \in B'$. Then the proof by contraposition is complete. 



















