---
title: "Problem Set 5"
author: "David Zynda"
date: "September 26, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 8.1

__Prove the Proposition__:

_Let X be a convex subset of $\mathbb{R}^k$. (a) Let $u$ be a utility function on $X$. Consider three bundles $x^0,x^1,$ and $y$ such that $u(x^0) \le u(y) \le u(x^1)$. For $t \in [0,1]$, let $x^t = tx^1 + (1-t)x_0$. If $u$ is continuous, then there exists some $t \in [0,1]$ such that $u(x^t) = u(y)$. (b) Let $\succsim$ be a complete and transitive preference on $X$. Consider three bundles $x^0, x^1$ and $y$ such that $x^0 \succsim y \succsim x^1$. For $t \in [0,1]$ let $x^t = tx^1 + (1 - t)x_0$. If $succsim$ is continuous, then there exists some $t \in [0,1]$ such that $x^t \sim y$._

__Proof__:

Case 1: _Trivially_ if $u(x^t) = u(x^0) = u(y)$ then $t = 0$. Otherwise, if $u(x^t) = u(x^1) = u(y)$ then $t=1$.


Case 2: $u(x^0) \ne u(y)$ and $u(y) \ne u(x^1)$


Define a set 

$$T^- = \{t \in [0,1]:u(x^t) \le u(y)\}$$
where $x^t = tx^1 + (1 - t)x_0$.

Then, define $t^* = \sup T^-$. Because this set $T^-$ contains $0$, it is nonempty. Additionally, it has an upper bound at $1$. Therefore, $t^*$ exists. Let $x^{t^*}$ be the convex combination of bundles $x_0$ and $x_1$ which correspond to $x^t$ defined at $t^*$. 

Show that it is not possible for $u(x^{t^*}) \ne u(y)$ such that $t^*$ is the least upper bound of $T^-$. 

First, suppose that $u(x^{t^*}) < u(y)$. Then, $t^* < 1$ because $u(x^{t^*}) < u(y) \le u(x^1)$ and we defined $x^t = tx^1 + (1-t)x_0$. We assumed that $u$ is a continuous function, thus there must exist some $\delta \in (x^0, x^{t^*})$ such that $u(x^t) < u(y)$ for all $t$ which guarantee a distance of $\delta$ from $x^{t^*}$. Then, $f(x^{t^*} + \frac{\delta}{2}) < u(y)$. Then, $t^*$ composing $x^{t^*}$ cannot be the least upper bound of $T^-$. 

Next, suppose that $u(x^{t^*}) > u(y)$. Then, $x^{t^*} > x^0$ and so $t^* > 0$ because $u(y) \ge u(x_0)$. Because $u$ is continuous, then there exists $\delta \in (x^0, x^{t^*})$ such that $f(x^{t}) > u(y)$ for all $t$ within a distance from $t*$. So, the interval $(x^{t^*} - \delta, x^{t^*}]$ is not contained in $T^-$. So, if $t^*$ from $x^{t^*}$ is an upper bound for $T^-$, then the $t^{**}$ comprising $x^{t^{**}} =  x^{t^*} - \delta$ is a lesser upper bound for $T^-$. Then $t^*$ cannot be the least upper bound. 

So, it follows that since it is not the case $u(x^{t^*}) < u(y)$ and it is also not the case $u(x^{t^*}) > u(y)$, it must be the case that:

$$u(x^{t^*}) = u(y)$$
for $t^* \in [0,1]$. 


_________________________________________________________________________________




Let $T = \{t \in [0,1] : y \succsim x^t\}$ where $x^t = tx^1 + (1 - t)x^0$. Since T is nonempy (containing 0) and bounded from above by $1$, there exists a supremum. Denote $t^* = \sup T$. It will be shown that by continuity of preferences, $t^*$ cannot be the least upper bound of $T$ if either $x^{t^*} \succ y$ or $y \succ x^{t^*}$. 

First, assume that $y \succ x^{t^*}$. Then, $\exists \delta > 0 : d(x^{t^*}, x') < \delta$. This implies that, by continuity, $y \succ x'$. Since $x' \in B_{\delta}(x)$, choose an $x' \succ x^{t^{*}}$. Then the $t^*$ is not the supremum of $T$ since $x^{t^*}$ generated by $t^*$ is not better than $x'$ which is not better than $y$. So, the $t^{**}$ generating $x' = t^{**}x^1 + (1-t^{**})x^0$ is the supremum of $T$. 

Now, suppose that $x^{t^*} \succ y$. By a similar argument, we know that there exists a $\delta > 0$ such that $d(x^{t^*}, x') < \delta$. This implies that, by continuity, $y \succ x'$. If $x' = x^{t^*} - \delta$, then the $t^*$ generating $x^{t^*}$ cannot be the supremum of $T$. Rather, the supremum would then be $t^{**}$ generating $x^{t^{**}} = x'$



## Problem 8.2

_Above it is proven, in the two-good case, that if a preference is complete, transitive, continuous and strictly increasing, the it has a utility representation. Prove the same thing in the more general case of $k$ goods. Then, show that if a utility function is continuous and strictly increasing, then it has a continuous and strictly increasing preference._


__Part (a)__


Define $Z = \{x \in \mathbb{R}^k : x_1= x_2 =...= x_k\}$, or the line at which each component in the grand set of alternatives $X$ are equal.  to one another. Then, define $e = \{1,1,...,1\} \in \mathbb{R}^k$ as the unit vector. So, for any $\alpha\in \mathbb{R}: \alpha \ge 0 \implies \alpha e \in Z$.

Let $x$ be a bundle. Then, for any $\hat{\alpha} e >> x: \hat{\alpha} e \succsim x$. Then, we know that $\alpha (x) \in [0, \hat{\alpha}] \implies \alpha (x) e \sim x$. This is because of $\succsim$ being strictly increasing and continuous. Because the preference is continuous, all upper and lower contour sets are closed. Because the upper and lower contour sets are closed and nonempty, there must be some scalar $\alpha$ such that $\alpha e \sim x$. Because the preference is strictly increasing, there must only be one. 

Then, call $\alpha (x)$ the utility function $u(x)$. So, $u(x)$ will assign a number to every bundle in $X$. 

Assume the following is true of two bundles $x, y: x \succsim y$. Then, $x \sim \alpha(x) e$ and $y \sim \alpha (y) e$. It follows that (by the assumption of strictly increasing):

$$\alpha(x) e \sim x \succsim y \sim \alpha(y) e \implies \alpha(x)  \ge \alpha(y)$$

This also goes the other way; if we start out with $\alpha(x) \ge \alpha(y)$ we know that $\alpha(x) e \ge \alpha(y) e$. Then:

$$x \sim \alpha(x) e \succsim  \alpha(y) e  \sim y$$

It can also be shown that beginning from a continuous preference can lead us to a continuous utility function. 

Let $x \in X$. For all $\varepsilon > 0$ there exists a $\delta > 0$ such that $d(x,y) < \delta \implies |u(x) - u(y)| < \varepsilon$. Then, $u(x) - \varepsilon < u(y) < u(x) + \varepsilon$.

For $u(x) - \varepsilon < u(y)$, we know that there is continuity if $u(x) \le \varepsilon$. If not, we know that $(u(x_1)-\varepsilon, ..., u(x_k) - \varepsilon) \prec x$. Then there similarly must exist a $\delta$ such that $d(x, y) < \delta$ implies that $(u(x_1)-\varepsilon, ..., u(x_k) - \varepsilon) \prec y$ as well. 

For the other case $u(y) < u(x) + \varepsilon$. Similar to above, we know that $(u(x_1)+\varepsilon, ...,u(x_k) + \varepsilon) \succ y$. Let the $\delta_n$ correspond to $u(x_n)+\varepsilon$. Then let $\delta = \min\{\delta_1, ..., \delta_n\}$ and then the preference will be continuous. 

__Part (b)__ We can also show that a continuous and strictly increasing preference can be derived from a utility function. 

Assume that a utility function is continuous and represents $\succsim$. Let $\delta$ be the difference between $u(x)$ and $u(y)$. I assume $u(x) > u(y)$. Therefore, $\delta > 0$. 

Let $x'$ be in the ball surrounding $x$, such that $x' \in B_{\delta'} (x)$. Then, $|u(x) - u(x')| < \delta '$. Similarly, let the same be of $y$ and $y' \in B_{\delta'} (y)$. Set $\delta' = \frac{\delta}{3}$. 

Then $\forall x' \in B_{\delta'} (x)$ $\forall y' \in B_{\delta'} (y)$:

$$u(x') - u(y') = u(x') - u(y') + u(x) - u(x) + u(y) - u(y) = u(x') - u(x) + u(x) - u(y) + u(y) - u(y')$$
$$\ge u(x) - u(y) - |u(x') - u(x)| - |u(y') - u(y)| \ge \delta - \delta' - \delta' = \delta'$$ 

$$u(x') - u(y') \ge \delta' \implies x' \succ y'$$

And so is true for any $x' \in B_{delta}(x)$ and $y' \in B_{\delta}(y)$. 














